# Generated by Django 5.1 on 2024-12-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
