# Generated by Django 5.1 on 2024-09-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BostonHousing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crim', models.FloatField()),
                ('zn', models.FloatField()),
                ('indus', models.FloatField()),
                ('chas', models.IntegerField()),
                ('nox', models.FloatField()),
                ('rm', models.FloatField()),
                ('age', models.FloatField()),
                ('dis', models.FloatField()),
                ('rad', models.IntegerField()),
                ('tax', models.FloatField()),
                ('ptratio', models.FloatField()),
                ('b', models.FloatField()),
                ('lstat', models.FloatField()),
                ('medv', models.FloatField()),
            ],
        ),
    ]
