# Generated by Django 5.1 on 2024-09-23 21:27

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0002_alter_bostonhousing_medv"),
    ]

    operations = [
        migrations.AddField(
            model_name="bostonhousing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2024, 9, 23, 21, 27, 15, 407131),
            ),
            preserve_default=False,
        ),
    ]
